import { ShortcutDefinition, ShortcutCategory } from './types';

// Default shortcuts - actions will be bound by the ShortcutManager
export const DEFAULT_SHORTCUTS: Omit<ShortcutDefinition, 'action'>[] = [
  // === FILE OPERATIONS ===
  {
    id: 'file.save',
    category: 'file',
    label: 'Save Workflow',
    description: 'Save current workflow changes',
    defaultKeys: ['Ctrl', 'S'],
    global: false,
  },
  {
    id: 'file.saveAs',
    category: 'file',
    label: 'Save As',
    description: 'Save workflow with a new name',
    defaultKeys: ['Ctrl', 'Shift', 'S'],
    global: false,
  },
  {
    id: 'file.export',
    category: 'file',
    label: 'Export Workflow',
    description: 'Export workflow as JSON',
    defaultKeys: ['Ctrl', 'E'],
    global: false,
  },

  // === EDIT OPERATIONS ===
  {
    id: 'edit.undo',
    category: 'edit',
    label: 'Undo',
    description: 'Undo last action',
    defaultKeys: ['Ctrl', 'Z'],
    global: false,
  },
  {
    id: 'edit.redo',
    category: 'edit',
    label: 'Redo',
    description: 'Redo last undone action',
    defaultKeys: ['Ctrl', 'Shift', 'Z'],
    global: false,
  },
  {
    id: 'edit.copy',
    category: 'edit',
    label: 'Copy',
    description: 'Copy selected nodes',
    defaultKeys: ['Ctrl', 'C'],
    global: false,
  },
  {
    id: 'edit.cut',
    category: 'edit',
    label: 'Cut',
    description: 'Cut selected nodes',
    defaultKeys: ['Ctrl', 'X'],
    global: false,
  },
  {
    id: 'edit.paste',
    category: 'edit',
    label: 'Paste',
    description: 'Paste copied nodes',
    defaultKeys: ['Ctrl', 'V'],
    global: false,
  },
  {
    id: 'edit.duplicate',
    category: 'edit',
    label: 'Duplicate',
    description: 'Duplicate selected nodes',
    defaultKeys: ['Ctrl', 'D'],
    global: false,
  },
  {
    id: 'edit.delete',
    category: 'edit',
    label: 'Delete',
    description: 'Delete selected nodes or edges',
    defaultKeys: ['Delete'],
    global: false,
  },
  {
    id: 'edit.selectAll',
    category: 'edit',
    label: 'Select All',
    description: 'Select all nodes',
    defaultKeys: ['Ctrl', 'A'],
    global: false,
  },
  {
    id: 'edit.deselect',
    category: 'edit',
    label: 'Deselect All',
    description: 'Deselect all nodes',
    defaultKeys: ['Escape'],
    global: false,
  },
  {
    id: 'edit.group',
    category: 'edit',
    label: 'Group Nodes',
    description: 'Group selected nodes together',
    defaultKeys: ['Ctrl', 'G'],
    global: false,
  },
  {
    id: 'edit.ungroup',
    category: 'edit',
    label: 'Ungroup Nodes',
    description: 'Ungroup selected group',
    defaultKeys: ['Ctrl', 'Shift', 'G'],
    global: false,
  },

  // === NAVIGATION ===
  {
    id: 'nav.commandPalette',
    category: 'navigation',
    label: 'Command Palette',
    description: 'Open command palette',
    defaultKeys: ['Ctrl', 'K'],
    global: true,
  },
  {
    id: 'nav.search',
    category: 'navigation',
    label: 'Search',
    description: 'Search in current context',
    defaultKeys: ['Ctrl', 'F'],
    global: true,
  },
  {
    id: 'nav.globalSearch',
    category: 'navigation',
    label: 'Global Search',
    description: 'Search across all workflows',
    defaultKeys: ['Ctrl', 'Shift', 'F'],
    global: true,
  },
  {
    id: 'nav.goToWorkflows',
    category: 'navigation',
    label: 'Go to Workflows',
    description: 'Navigate to workflows list',
    defaultKeys: ['G', 'W'],
    global: true,
  },
  {
    id: 'nav.goToTemplates',
    category: 'navigation',
    label: 'Go to Templates',
    description: 'Navigate to templates gallery',
    defaultKeys: ['G', 'T'],
    global: true,
  },
  {
    id: 'nav.goToSettings',
    category: 'navigation',
    label: 'Go to Settings',
    description: 'Navigate to settings',
    defaultKeys: ['G', 'S'],
    global: true,
  },

  // === VIEW ===
  {
    id: 'view.zoomIn',
    category: 'view',
    label: 'Zoom In',
    description: 'Zoom in on canvas',
    defaultKeys: ['Ctrl', '='],
    global: false,
  },
  {
    id: 'view.zoomOut',
    category: 'view',
    label: 'Zoom Out',
    description: 'Zoom out on canvas',
    defaultKeys: ['Ctrl', '-'],
    global: false,
  },
  {
    id: 'view.fitView',
    category: 'view',
    label: 'Fit View',
    description: 'Fit all nodes in view',
    defaultKeys: ['Ctrl', '0'],
    global: false,
  },
  {
    id: 'view.resetZoom',
    category: 'view',
    label: 'Reset Zoom',
    description: 'Reset zoom to 100%',
    defaultKeys: ['Ctrl', '1'],
    global: false,
  },
  {
    id: 'view.toggleMinimap',
    category: 'view',
    label: 'Toggle Minimap',
    description: 'Show/hide minimap',
    defaultKeys: ['Ctrl', 'M'],
    global: false,
  },
  {
    id: 'view.toggleSidebar',
    category: 'view',
    label: 'Toggle Sidebar',
    description: 'Show/hide node panel',
    defaultKeys: ['Ctrl', 'B'],
    global: false,
  },
  {
    id: 'view.toggleChat',
    category: 'view',
    label: 'Toggle Chat',
    description: 'Show/hide collaboration chat',
    defaultKeys: ['Ctrl', 'Shift', 'C'],
    global: false,
  },

  // === DEBUG ===
  {
    id: 'debug.run',
    category: 'debug',
    label: 'Run Workflow',
    description: 'Execute the workflow',
    defaultKeys: ['F5'],
    global: false,
  },
  {
    id: 'debug.stop',
    category: 'debug',
    label: 'Stop Execution',
    description: 'Stop running workflow',
    defaultKeys: ['Shift', 'F5'],
    global: false,
  },
  {
    id: 'debug.runSelected',
    category: 'debug',
    label: 'Run Selected Node',
    description: 'Execute only the selected node',
    defaultKeys: ['F6'],
    global: false,
  },
  {
    id: 'debug.toggleBreakpoint',
    category: 'debug',
    label: 'Toggle Breakpoint',
    description: 'Add/remove breakpoint on selected node',
    defaultKeys: ['F9'],
    global: false,
  },

  // === COLLABORATION ===
  {
    id: 'collab.addComment',
    category: 'collaboration',
    label: 'Add Comment',
    description: 'Add a comment at cursor position',
    defaultKeys: ['C'],
    global: false,
  },
  {
    id: 'collab.showActivity',
    category: 'collaboration',
    label: 'Show Activity',
    description: 'Show recent activity on this workflow',
    defaultKeys: ['A'],
    global: false,
  },
];

// Category labels for UI
export const CATEGORY_LABELS: Record<ShortcutCategory, string> = {
  file: 'File',
  edit: 'Edit',
  navigation: 'Navigation',
  view: 'View',
  debug: 'Debug',
  collaboration: 'Collaboration',
  custom: 'Custom',
};
